fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: black format
        entry: poetry run black .
        types:
          - python
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort lint
        entry: poetry run isort .
        types:
          - python
        language: system
  # - repo: local
  #   hooks:
  #     - id: system
  #       name: MyPy
  #       entry: mypy .
  #       pass_filenames: false
  #       language: system
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [ python ]